# make_icons.py
# Run this ONCE to generate the app icons
import base64

# Simple purple 192x192 and 512x512 icons (Base64 encoded to avoid external dependencies)
icon_192 = b'iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAMAAABlApw1AAAAQlBMVEHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPH///+02480AAAAFXRSTlMAQ80wwC/N0P301/D7/GDA/fq68/x6u24BAAAApElEQVR4nO3XsQ2AMAwAwch/6YwsRwIpEClT5O5OT9fZ9XbtB/gYIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIEDAAwMqCwE0Dq6s6AAAAABJRU5ErkJggg=='
icon_512 = b'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAMAAADDpiTIAAAAQlBMVEHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPHVZPH///+02480AAAAFXRSTlMAQ80wwC/N0P301/D7/GDA/fq68/x6u24BAAAA1klEQVR4nO3BAQ0AAADCoPdPbQ8HFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMvtWwAAW2106kAAAAASUVORK5CYII='

with open("icon-192.png", "wb") as f:
    f.write(base64.b64decode(icon_192))

with open("icon-512.png", "wb") as f:
    f.write(base64.b64decode(icon_512))

print("✅ Icons created: icon-192.png and icon-512.png")